version: '3.8'

services:
  mysql:
    image: mysql/mysql-server:8.0
    restart: on-failure
    volumes:
      - "dbdata:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    ports:
      - ${DOCKER_MYSQL_PORT:-3310}:3306
    networks:
      - backend
  php-fpm:
    build: .
    restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@mysql:3306/${DATABASE_NAME}?serverVersion=8.0.0
    links:
      - mysql
    volumes:
      - ".:/var/www"
    networks:
      - backend
      - frontend

  nginx:
    image: nginx:latest
    restart: on-failure
    depends_on:
      - php-fpm
    volumes:
      - ".:/var/www"
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - 8084:80
    networks:
      - backend
      - frontend

networks:
  frontend:
  backend:
volumes:
  dbdata:
    name: ${DOCKER_MYSQL_VOLUME:-dbdata}
